image: node:18

definitions:
  steps:
    - step: &build-webchat
        name: Build Web Chat
        caches:
          - node
        script:
          - cd aeon.web.chat
          - npm ci
          - npm run build
        artifacts:
          - aeon.web.chat/dist/**
    
    - step: &deploy-to-s3
        name: Deploy to S3
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-southeast-1'
              S3_BUCKET: $S3_BUCKET_NAME
              LOCAL_PATH: 'aeon.web.chat/dist'
              DELETE_FLAG: 'true'
              CACHE_CONTROL: 'public, max-age=31536000'
              EXTRA_ARGS: '--exclude "index.html"'
          # Upload index.html separately with no-cache
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-southeast-1'
              S3_BUCKET: $S3_BUCKET_NAME
              LOCAL_PATH: 'aeon.web.chat/dist/index.html'
              CACHE_CONTROL: 'no-cache, no-store, must-revalidate'
    
    - step: &invalidate-cloudfront
        name: Invalidate CloudFront Cache
        script:
          - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-southeast-1'
              DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID
              PATHS: '/*'

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - node
        script:
          - cd aeon.web.chat
          - npm ci
          - npm run build
  
  branches:
    main:
      - step: *build-webchat
      - step: *deploy-to-s3
      - step: *invalidate-cloudfront
    
    develop:
      - step: *build-webchat
      - step:
          name: Deploy to Dev S3
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: $S3_BUCKET_NAME_DEV
                LOCAL_PATH: 'aeon.web.chat/dist'
                DELETE_FLAG: 'true'
  
  custom:
    deploy-production:
      - step: *build-webchat
      - step: *deploy-to-s3
      - step: *invalidate-cloudfront
